import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import AppSidebar from "@/components/app-sidebar";
import ConvexClientProvider from "@/components/convex-client-provider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "M3 Chat",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ConvexClientProvider>
			<html lang="en">
				<body
					className={`dark ${geistSans.variable} ${geistMono.variable} antialiased overscroll-none`}
				>
					<SidebarProvider>
						<AppSidebar />
						<main className="flex-1 overscroll-none">
							<SidebarTrigger className="cursor-pointer fixed" />
							{children}
						</main>
					</SidebarProvider>
				</body>
			</html>
		</ConvexClientProvider>
	);
}
